### ISSUE TITLE
Touch to set waypoint destination flight mode

### ISSUE THREAD

**Issue by chucky-whiskers** [yaapu/EthosMappingWidget#6]
I want to be able to tap the map and have my plane go to those coordinates. While there are probably logic switch options available, working with a firmware developer would be awesome if your lua could basically be a touchscreen waypoint creator. The flight mode would need to have defined altitude options such as a ceiling/travel altitude, a destination altitude, and a quick undo waypoint placement option. I feel like all the technology is there with maps being available, gps coordinates being available, waypoint missions already possible. The big thing is being able to map the touch screen function into a usable signal base off sat tiles displayed. Then that information would need to be sent similar to how mavlink would send a "next waypoint" from mission planner. It's just a matter of setting it up.

**Comment by yaapu** [comment]
this is not a planned feature, you can however try to submit a patch if you fell like giving a try to it.
It would require a lot of coding both on the widget and on ardupilot, there's no protocol right now that could carry such a message (there's no mavlink between the radio and the FC running ardupilot)
